inputDirectory: input
outputDirectory: output
templateDirectory: template
title: My blog
theme: https://github.com/dejandjenic/template.test.git
description: 
additionalItems: 
ga: G-W99CWL1C9H
additionalFooterLinks: 
additionalNavLinks: 
