inputDirectory: input
outputDirectory: output
templateDirectory: template
title: Welcome to Dejan's Blog
theme: MonoChrome
description: Empowering Tech Enthusiasts, One Byte at a Time.
additionalItems: 
ga: G-DKBCRZ77DR
additionalFooterLinks: 
additionalNavLinks: 
hostedurl: https://www.dejandjenic.com
generic: 
  about:
    text: I'm Dejan Đenić, a seasoned software developer with over 20 years of experience, specializing in .NET backend development, NoSQL databases, microservices, CI/CD, and containerization. I have management experience, emphasizing secure API development. Through my blog and LinkedIn, I share insights, fostering a community of developers, and promoting effective team leadership in software development.
    image: /images/me.jpg
  just-software:
    id: 6nNUpUgInhQ21pZIDKGK
    key: lxyi4d73WqU2fG8d1OJz5VKy+On6ElPTTxDTQMZW6PoWaX0McqWaXJZpWmoBAv6jcnnRaN3fFlpxJSFCpjerMOT2xLq/+Oa+hr8X0ilsOvcRhQ+zckhxrvkZ/iDIS4MnZjDmv0vlAS5z4GcJMad+lakHynGS/s9jFqAcBVgqfc7gGOy2S7U80UJ+apeztimumsNH9tYb/d0adBMYk+/gqnGj26891OnnU2XH60t8VOIiehjdopG1Lk39IIwdYd6BdIu+nBOHS1EUpJ6zvENYw1p+fBvjuChpreSvxNlyVSLuCNkxKYlp4x4oAEY0t7Qkv0R0zABzXS3td5wUC7Mev9xip0g2aBDSjbCtMIGxIvglY13bxCwfZE06U//8n5wFTscnUmiPKBYf6PUMJFzrHW3dzGTz+fVLiIWbHStvHeXyTUzwcmELjQhzWMT92g1PQnUJGfk18YcifPQRiW05aPVxqPLU3nY7Qe3jNTKPhx/C6TtHXeb64IuCNbGWfaxK
  title-override: Dejan's Blog - Empowering Tech Enthusiasts, One Byte at a Time.
lang: en
linkedin: https://www.linkedin.com/in/dejandjenic/
twitter: https://twitter.com/dejandjenic
