inputDirectory: input
outputDirectory: output
templateDirectory: template
title: My blog
theme: SolidState
description: 
additionalItems: 
ga: G-W99CWL1C9H
additionalFooterLinks: 
additionalNavLinks: 
