name: GenesysSSG

on:
  push:
    branches:
    - main  # default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'
    - name: Install GenesysSSG
      run: dotnet tool install --tool-path . GenesysSSG
    - name: Publish blog
      run: ./genesysssg
    - name: Configure public domain
      run: echo "www.dejandjenic.com" >> ./output/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      env:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages  # deploying branch
        publish_dir: ./output
